import type { Tile } from './types';
import {
  createPortalTile,
  TILE_FLOOR as FLOOR,
  TILE_START as START,
  TILE_WALL as WALL,
} from './utils/maze/tileConstants';

export const levelHome: Tile[][] = [
  [WALL, WALL, WALL, WALL, WALL, createPortalTile('projects', 'PROJECTS', '#00ccff'), WALL, WALL, WALL, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, FLOOR, WALL, FLOOR, WALL, WALL, FLOOR, WALL],
  [WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL],
  [createPortalTile('skills', 'SKILLS', '#ff00ff'), FLOOR, WALL, FLOOR, FLOOR, START, FLOOR, FLOOR, WALL, FLOOR, createPortalTile('contact', 'CONTACT', '#ffff00')],
  [WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, FLOOR, WALL, FLOOR, WALL, WALL, FLOOR, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, createPortalTile('endless', 'ENDLESS', '#00ff88'), WALL, WALL, WALL, WALL, WALL],
];

export const levelProjects: Tile[][] = [
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, START, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL],
  [WALL, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL],
  [WALL, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, createPortalTile('home', 'HOME', '#ffffff'), WALL, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
];

export const levelSkills: Tile[][] = [
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, START, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, createPortalTile('home', 'HOME', '#ffffff'), WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
];

export const levelContact: Tile[][] = [
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, WALL, START, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL],
  [WALL, WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL, WALL],
  [WALL, WALL, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL],
  [WALL, WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL],
  [WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL, WALL, WALL],
  [WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL, WALL],
  [WALL, WALL, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, WALL, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, createPortalTile('home', 'HOME', '#ffffff'), WALL, WALL, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
];

export const levelRetry: Tile[][] = [
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL],
  [WALL, createPortalTile('endless/retry', 'RETRY', '#ff4444'), WALL, FLOOR, WALL, createPortalTile('home', 'HOME', '#ffffff'), WALL],
  [WALL, FLOOR, FLOOR, START, FLOOR, FLOOR, WALL],
  [WALL, WALL, WALL, WALL, WALL, WALL, WALL],
];
